### ISSUE TITLE
Unknown error when adding media to Sonos Card

### ISSUE THREAD

**Issue by drgregharris** [punxaphil/custom-sonos-card#387]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

Latest release, fresh home assistant install

Chrome and MacOS Sonoma 14.5. I've tried in Safari and get the same error.

I’ve installed the card and if I start music on my speakers from the Sonos app, the card updates and I can control the music. However, when I try to browse media and click Spotify, I get an unknown error. I’ve checked to make sure all the playlists have album art. If I play music through the Spotify card, everything works fine and I can see my playlists, etc but obviously can’t send this to the Sonos speakers. Any insight? I’ve pasted the log below.  Not sure if it's a Spotify integration issue or a Sonos integration issue.  

Logger: homeassistant.components.websocket_api.http.connection
Source: components/spotify/browse_media.py:181
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:10:31 AM (5 occurrences)
Last logged: 10:54:57 AM

[547729937680] Error handling message: Unknown error (unknown_error) Greg from 182.168.1.6 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36)
[547487001056] Error handling message: Unknown error (unknown_error) Greg from 182.168.1.6 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1308, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_player.py", line 776, in async_browse_media
    return await media_browser.async_browse_media(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sonos/media_browser.py", line 115, in async_browse_media
    return await spotify.async_browse_media(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/spotify/browse_media.py", line 181, in async_browse_media
    or not isinstance(entry.runtime_data, HomeAssistantSpotifyData)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'HomeAssistantSpotifyData' is not defined

Thanks in advance.

**Comment by punxaphil** [comment]
Not sure I follow fully. Can you make a recording of the error?

**Comment by unlight666** [comment]
Exact same error here.

**Comment by punxaphil** [comment]
Does it work in the standard media player?
http://homeassistant.local/media-browser/browser

**Comment by drgregharris** [comment]
Screen capture

https://github.com/punxaphil/custom-sonos-card/assets/16406726/3c850602-8e46-482d-88c9-49148fc18389

**Comment by punxaphil** [comment]
You need to get it working in the built in media player first

**Comment by punxaphil** [comment]
Make sure you:

- [ ] are using the standard Spotify integration (https://www.home-assistant.io/integrations/spotify/)
- [ ] Spotify is working in the built in media player (http://homeassistant.local/media-browser/browser).

Please reopen this ticket if you still see an issue, even when you have the above two working.
