### ISSUE TITLE
"Unknown error" when trying to download (all versions)

### ISSUE THREAD

**Issue by NekoMana1** [punxaphil/custom-sonos-card#560]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
All

**Last working release (if known):**
None

**Browser and Operating System:**
Chrome/Safari, MacOS

**Description of problem:**
When trying to download the Sonos Card, i get an error Message "Unknown error". When checking the Logs, i can see following error:

**Javascript errors shown in the web inspector (if applicable):**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/plugin.py:165
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:16:15 (4 occurrences)
Last logged: 20:46:12

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_download_repository(ref=msg.get("version"))
  File "/config/custom_components/hacs/repositories/base.py", line 1436, in async_download_repository
    await self.async_install(version=ref)
  File "/config/custom_components/hacs/repositories/base.py", line 890, in async_install
    await self._async_post_install()
  File "/config/custom_components/hacs/repositories/base.py", line 909, in _async_post_install
    await self.async_post_installation()
  File "/config/custom_components/hacs/repositories/plugin.py", line 65, in async_post_installation
    await self.update_dashboard_resources()
  File "/config/custom_components/hacs/repositories/plugin.py", line 208, in update_dashboard_resources
    url = self.generate_dashboard_resource_url()
  File "/config/custom_components/hacs/repositories/plugin.py", line 165, in generate_dashboard_resource_url
    if "/" in filename:
       ^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Additional information:**
I have tried multiple versions of the Sonos Card, but i get the same error with all of them. I've updated the OS and Core of HA to the newest version, but it didn't solve the issue. Also have restarted the HA Server.
I'm assuming this has to be some kind of issue in my specific HA install, but other Cards from HACS work fine, so i'm not sure what the issue is here.

**Comment by jeeesper** [comment]
same issue for me.

**Comment by punxaphil** [comment]
Thanks for reporting. Some issue with creating releases.
Please use v8.3.0

**Comment by jeeesper** [comment]
Thanks for the quick fix. 8.3.0 is working.

**Comment by NekoMana1** [comment]
@punxaphil 
Can confirm, 8.3.0 worked for me as well.

Thanks :)
